# ==========================================
#   please do NOT edit this file unless
#   you know what you're doing :)
# ==========================================

from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import re
import pandas as pd
import requests
import streamlit as st
import streamlit.components.v1 as components
from msal_streamlit_authentication import msal_authentication

# import environment configs
import config

# page config
st.set_page_config(
    page_title="ServiceDesk Plus Compliance Automation Tool", layout="wide", page_icon="💻"
)

# azure SSO secrets check
try:
    azure_client_id = st.secrets["azure"]["client_id"]
    azure_tenant_id = st.secrets["azure"]["tenant_id"]
except Exception:
    st.error(
        "Azure AD secrets missing. please configure 'client_id' and 'tenant_id'"
        " in Streamlit Cloud Secrets."
    )
    st.stop()

# title
st.markdown(
    "<h1 style='text-align: center;'>ServiceDesk Plus Compliance Automation Tool</h1>",
    unsafe_allow_html=True,
)

banner_spot = st.empty()
login_spot = st.empty()

# render MSAL auth inside container
with login_spot:
    col1, col2, col3 = st.columns([1, 1, 1])
    with col2:
        login_token = msal_authentication(
            auth={
                "clientId": azure_client_id,
                "authority": (
                    f"https://login.microsoftonline.com/{azure_tenant_id}"
                ),
                "redirectUri": "/",
                "postLogoutRedirectUri": "/",
            },
            cache={
                "cacheLocation": "sessionStorage",
                "storeAuthStateInCookie": False,
            },
            key="msal_auth",
        )

# if not logged in, show warning and stop execution
if not login_token:
    banner_spot.markdown(
        """
        <div style="
            background-color: rgba(114, 169, 104, 0.15); 
            border: 1px solid rgba(114, 169, 104, 0.3);
            color: #90a968;
            padding: 14px 20px;
            border-radius: 8px;
            text-align: center;
            font-size: 16px;
            margin-bottom: 20px;
        ">
            Please sign in with your normal account to access this portal.
        </div>
    """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <style>
        iframe[title*="msal_streamlit_authentication"] {
            height: 70px !important;
            min-height: 70px !important;
        }
        </style>
    """,
        unsafe_allow_html=True,
    )

    js_styler = """
    <script>
        function styleMsalButton() {
            const iframes = parent.document.querySelectorAll('iframe');
            iframes.forEach(iframe => {
                try {
                    if (iframe.contentDocument.body) {
                        iframe.contentDocument.body.style.margin = '0';
                        iframe.contentDocument.body.style.padding = '4px 0';
                    }

                    const btn = iframe.contentDocument.querySelector('button');
                    if (btn) {
                        btn.style.backgroundColor = '#90a968';
                        btn.style.color = '#000000';
                        btn.style.boxShadow = '4px 4px 4px #90a96880';
                        btn.style.fontSize = '24px';
                        btn.style.fontWeight = 'bold';
                        btn.style.padding = '12px 36px';
                        btn.style.border = 'none';
                        btn.style.borderRadius = '8px';
                        btn.style.cursor = 'pointer';
                        btn.style.width = '100%';
                        btn.style.boxSizing = 'border-box';
                    }
                } catch(e) {
                    // cross-origin catch
                }
            });
        }
        setInterval(styleMsalButton, 200);
    </script>
    """
    components.html(js_styler, height=0)
    st.stop()

# extract user details after login
account_info = login_token.get("account", {})
user_email = account_info.get("username", "Engineer")
user_name = account_info.get("name", "User")

st.sidebar.success(f"Logged in as:\n**{user_name}**\n({user_email})")

# helper functions
def clean_and_get_int(value):
    """integer converter for CSV entries"""
    if pd.isna(value):
        return 0
    val_str = str(value).strip()
    if not val_str or val_str.lower() == "nan":
        return 0
    if "." in val_str:
        val_str = val_str.split(".")[0]
    digits = re.findall(r"\d+", val_str)
    return int(digits[0]) if digits else 0

# SDP OAUTH
def get_access_token():
    """exchange the refresh token for a live 1-hour access token."""
    url = f"{st.secrets['sdp']['accounts_url']}/oauth/v2/token"
    payload = {
        "grant_type": "refresh_token",
        "client_id": st.secrets["sdp"]["client_id"],
        "client_secret": st.secrets["sdp"]["client_secret"],
        "refresh_token": st.secrets["sdp"]["refresh_token"],
    }
    response = requests.post(url, data=payload)
    if response.status_code == 200:
        return response.json().get("access_token")
    else:
        raise Exception(f"Failed to obtain OAuth access token: {response.text}")

# asset lookup logic
def get_asset_details(pc_name, access_token):
    """Query SDP IT Computers/Assets module using OAuth."""
    headers = {
        "Authorization": f"Zoho-oauthtoken {access_token}",
        "Accept": "application/vnd.manageengine.sdp.v3+json",
    }

    raw_pc = str(pc_name).strip()
    base_pc = raw_pc.split(".")[0]

    search_candidates = config.get_search_candidates(base_pc)

    endpoints = [
        f"{st.secrets['sdp']['api_domain']}/api/v3/assets",
        f"{st.secrets['sdp']['api_domain']}/api/v3/workstations",
    ]

    for endpoint in endpoints:
        for candidate in search_candidates:
            input_data = {
                "list_info": {
                    "search_fields": {"name": candidate},
                    "fields_required": ["name", "state", "user"],
                }
            }

            try:
                res = requests.get(
                    endpoint,
                    headers=headers,
                    params={"input_data": json.dumps(input_data)},
                    verify=True,
                )
                if res.status_code == 200:
                    data = res.json()
                    assets = data.get("assets") or data.get("workstations", [])
                    if assets:
                        asset = assets[0]
                        
                        state_obj = asset.get("state", {})
                        state = state_obj.get("name", "Unknown") if isinstance(state_obj, dict) else str(state_obj)
                        
                        user_info = asset.get("user")
                        user_name = (
                            user_info.get("name", "Unassigned / In Store")
                            if isinstance(user_info, dict) and user_info.get("name")
                            else "Unassigned / In Store"
                        )
                        return state, user_name
            except Exception:
                continue

    return "Not Found in SDP", "Unknown"

# ticket search logic
def search_existing_ticket(pc_name, access_token):
    """
    searches SDP for an open compliance check ticket for the specified PC
    returns the internal numerical id if an open ticket exists, otherwise None
    """
    endpoint = f"{st.secrets['sdp']['api_domain']}/api/v3/requests"

    headers = {
        "Authorization": f"Zoho-oauthtoken {access_token}",
        "Accept": "application/vnd.manageengine.sdp.v3+json",
    }

    base_pc = str(pc_name).split(".")[0].strip().upper()
    # modify the ticket subject here
    # ensure you apply the exact same to line ~293 as well (under 'ticket creation logic' section)
    expected_subject = f"IT Action Required: Compliance Check for {base_pc}"

    input_data = {
        "list_info": {
            "search_fields": {
                "subject": expected_subject
            },
            "fields_required": ["id", "display_id", "subject", "status"],
        }
    }

    try:
        res = requests.get(
            endpoint,
            headers=headers,
            params={"input_data": json.dumps(input_data)},
            verify=True,
        )

        if res.status_code == 200:
            requests_list = res.json().get("requests", [])
            
            for req in requests_list:
                status_name = req.get("status", {}).get("name", "").lower()
                
                # ignore closed/resolved tickets
                if status_name not in ["closed", "resolved", "cancelled"]:
                    return req.get("id"), req.get("display_id")

    except Exception as e:
        st.warning(f"Error checking existing SDP tickets for {base_pc}: {str(e)}")

    return None, None

# ticket creation logic
def create_sdp_ticket(
    pc_name,
    updates,
    device_scan,
    asset_state,
    assigned_user,
    description_template,
    access_token,
):
    """submit a ticket payload using a pre-fetched access token"""
    endpoint = f"{st.secrets['sdp']['api_domain']}/api/v3/requests"

    headers = {
        "Authorization": f"Zoho-oauthtoken {access_token}",
        "Accept": "application/vnd.manageengine.sdp.v3+json",
    }

    site_name = config.get_site_from_pc(pc_name)
    # modify the ticket subject here
    # ensure it replicates the subject under 'ticket search logic' exactly - otherwise duplicate ticket creation occurs
    subject = f"IT Action Required: Compliance Check for {pc_name}"

    raw_description = description_template.format(
        PCName=pc_name,
        Updates=updates if updates != "" else "0",
        DeviceScan=device_scan if device_scan != "" else "0",
        AssetState=asset_state,
        AssignedUser=assigned_user,
        Site=site_name,
    )

    sdp_description = raw_description.replace("\n", "<br>")

    # this can be modified in `config.py` under section "7. SERVICEDESK PLUS (SDP) PAYLOAD DEFAULTS"
    payload = {
        "request": {
            "subject": subject,
            "description": sdp_description,
            "requester": {"email_id": config.SDP_REQUESTER_EMAIL},
            "category": {"name": config.SDP_CATEGORY},
            "request_type": {"name": config.SDP_REQUEST_TYPE},
            "site": {"name": site_name},
            "mode": {"name": config.SDP_MODE},
            "impact": {"name": config.SDP_IMPACT},
            "urgency": {"name": config.SDP_URGENCY},
            "priority": {"name": config.SDP_PRIORITY},
        }
    }

    data = {"input_data": json.dumps(payload)}

    return requests.post(endpoint, headers=headers, data=data, verify=True)

# note creation logic 
def add_note_to_ticket(ticket_id, note_text, access_token):
    """appends a compliance update note to an existing SDP ticket"""
    endpoint = f"{st.secrets['sdp']['api_domain']}/api/v3/requests/{ticket_id}/notes"

    headers = {
        "Authorization": f"Zoho-oauthtoken {access_token}",
        "Accept": "application/vnd.manageengine.sdp.v3+json",
    }

    input_data = {
        "request_note": {
            "mark_first_response": False,
            "add_to_linked_requests": False,
            "notify_technician": False,
            "show_to_requester": False,
            "description": note_text
        }
    }

    try:
        res = requests.post(
            endpoint,
            headers=headers,
            data={"input_data": json.dumps(input_data)},
            verify=True,
        )
        if res.status_code in [200, 201]:
            return True
        else:
            st.error(f"SDP Error (Ticket #{ticket_id}): Code {res.status_code} - {res.text}")
            return False
    except Exception as e:
        st.error(f"Failed to add note to ticket #{ticket_id}: {str(e)}")
        return False

# MAIN APP UI

# file uploaders
col1, col2 = st.columns(2)

with col1:
    st.subheader("1. Windows Updates Report")
    updates_file = st.file_uploader(
        "Upload 'Windows Updates Required.csv'", type=["csv"]
    )

with col2:
    st.subheader("2. Endpoint Scan Report")
    scan_file = st.file_uploader(
        "Upload 'Endpoint Last Scan Report.csv'", type=["csv"]
    )

if updates_file and scan_file:
    try:
        # process updates.csv using config skiprows
        df_updates_raw = pd.read_csv(updates_file, skiprows=config.UPDATES_SKIPROWS, header=None)
        num_cols_updates = df_updates_raw.shape[1]
        df_updates_raw.columns = [
            f"H{i}" for i in range(1, num_cols_updates + 1)
        ]

        # process scan report using config skiprows
        df_scan_raw = pd.read_csv(scan_file, skiprows=config.SCAN_REPORT_SKIPROWS, header=None)
        num_cols_scan = df_scan_raw.shape[1]
        df_scan_raw.columns = [f"H{i}" for i in range(1, num_cols_scan + 1)]

        # merge & filter logic
        merged_results = {}

        for _, row in df_updates_raw.iterrows():
            pc_name = str(row.get(config.UPDATES_PC_NAME_COL, "")).strip().upper()
            if (
                pc_name
                and pc_name != "NAN"
                and "COMPUTER" not in pc_name
                and "DEVICE" not in pc_name
            ):
                updates_count = clean_and_get_int(row.get(config.UPDATES_COUNT_COL))

                if updates_count >= config.MIN_MISSING_UPDATES:
                    if pc_name not in merged_results:
                        merged_results[pc_name] = {
                            "PCName": pc_name,
                            "Updates": "",
                            "DeviceScan": "",
                        }
                    merged_results[pc_name]["Updates"] = updates_count

        for _, row in df_scan_raw.iterrows():
            pc_name = str(row.get(config.SCAN_PC_NAME_COL, "")).strip().upper()
            if (
                pc_name
                and pc_name != "NAN"
                and "COMPUTER" not in pc_name
                and "DEVICE" not in pc_name
            ):
                scan_days = clean_and_get_int(row.get(config.SCAN_DAYS_COL))
                if scan_days >= config.MIN_INACTIVE_DAYS:
                    if pc_name not in merged_results:
                        merged_results[pc_name] = {
                            "PCName": pc_name,
                            "Updates": "",
                            "DeviceScan": "",
                        }
                    merged_results[pc_name]["DeviceScan"] = scan_days

        initial_df = pd.DataFrame(merged_results.values())
        if not initial_df.empty:
            initial_df = initial_df.sort_values(by="PCName").reset_index(
                drop=True
            )
        else:
            initial_df = pd.DataFrame(columns=["PCName", "Updates", "DeviceScan"])

        # review table
        st.markdown("---")
        st.subheader("Flagged Machines Review & Filtering")
        st.info(
            "**Instructions for Engineers**: To remove a machine, click the"
            " checkbox on its row and press the **Delete** key on your keyboard."
        )

        final_df = st.data_editor(
            initial_df,
            use_container_width=True,
            num_rows="dynamic",
            disabled=["PCName", "Updates", "DeviceScan"],
        )

        csv_output = final_df.to_csv(index=False).encode("utf-8")
        st.download_button(
            label="Download Merged 'Flagged-PCs.csv'",
            data=csv_output,
            file_name="Flagged-PCs.csv",
            mime="text/csv",
        )

        # SDP API dispatch system
        st.markdown("---")
        st.subheader("Dispatch Tickets to ServiceDesk")

        # session state flag to track emergency stop requests
        if "stop_requested" not in st.session_state:
            st.session_state.stop_requested = False

        # session state list to hold light backup logs
        if "dispatch_logs" not in st.session_state:
            st.session_state.dispatch_logs = []

        # worker function to process a single PC concurrently
        def process_single_pc(row_tuple, access_token, ticket_template):
            _, row = row_tuple
            pc = row["PCName"]
            updates = row["Updates"]
            device_scan = row["DeviceScan"]

            # lookup asset state/user in SDP
            asset_state, assigned_user = get_asset_details(pc, access_token)

            # search for existing open ticket for this machine
            existing_ticket_id, display_id = search_existing_ticket(pc, access_token)

            # ticket exists -> append note
            if existing_ticket_id:
                note_text = config.get_note_template(updates, device_scan, asset_state, assigned_user)
                note_success = add_note_to_ticket(existing_ticket_id, note_text, access_token)
                if note_success:
                    return {
                        "status": "update",
                        "html": f"""<div style="background-color: rgba(52, 152, 219, 0.15); border: 1px solid rgba(52, 152, 219, 0.3); color: #5dade2; padding: 10px 16px; border-radius: 6px; margin-bottom: 10px; font-size: 14px;">Updated Ticket <strong>#{display_id}</strong> for <strong>{pc}</strong></div>""",
                        "log": f"Updated Ticket **#{display_id}** for **{pc}**",
                    }
                else:
                    return {
                        "status": "fail",
                        "error_msg": f"Failed to append note to Ticket **#{display_id}** for **{pc}**",
                        "log": f"FAILED: Note append to Ticket **#{display_id}** for **{pc}**",
                    }
            else:
                # no existing ticket -> create new ticket
                try:
                    res = create_sdp_ticket(
                        pc, updates, device_scan, asset_state, assigned_user, ticket_template, access_token
                    )
                    if res.status_code in [200, 201]:
                        res_data = res.json()
                        request_obj = res_data.get("request", {})
                        ticket_id = (
                            request_obj.get("display_id")
                            or request_obj.get("workorder_id")
                            or request_obj.get("id", "N/A")
                        )
                        return {
                            "status": "create",
                            "html": f"""<div style="background-color: rgba(142, 68, 173, 0.15); border: 1px solid rgba(142, 68, 173, 0.3); color: #a569bd; padding: 10px 16px; border-radius: 6px; margin-bottom: 10px; font-size: 14px;">Created Ticket <strong>#{ticket_id}</strong> for <strong>{pc}</strong></div>""",
                            "log": f"Created Ticket **#{ticket_id}** for **{pc}**",
                        }
                    else:
                        return {
                            "status": "fail",
                            "error_msg": f"Failed to log ticket for **{pc}**. Status code: **{res.status_code}**",
                            "log": f"FAILED: Ticket creation for **{pc}**",
                        }
                except Exception as err:
                    return {
                        "status": "fail",
                        "error_msg": f"Error connecting to SDP for **{pc}**: {str(err)}",
                        "log": f"ERROR: **{pc}** - {str(err)}",
                    }

        # admin check for template editing
        if user_email.lower() in [email.lower() for email in config.ADMIN_USERS]:
            ticket_template = st.text_area(
                "Configure Ticket Description Template",
                value=config.DEFAULT_TICKET_TEMPLATE,
                height=240,
            )
        else:
            ticket_template = config.DEFAULT_TICKET_TEMPLATE
            with st.expander("View Ticket Description Template (Read-Only)"):
                st.caption("Only system administrators can edit this template.")
                st.code(config.DEFAULT_TICKET_TEMPLATE, language="text")

        # action buttons layout
        btn_col1, btn_col2 = st.columns([2, 1])

        with btn_col1:
            start_logging = st.button("Log Tickets via SDP", type="secondary")

        with btn_col2:
            if st.button("**EMERGENCY STOP**", type="primary"):
                st.session_state.stop_requested = True

        if start_logging:
            st.session_state.stop_requested = False
            st.session_state.dispatch_logs = []

            if final_df.empty:
                st.warning("The dispatch list is empty. No tickets to generate.")
                st.stop()

            # verify SDP OAuth secrets exist
            try:
                _ = st.secrets["sdp"]["client_id"]
                _ = st.secrets["sdp"]["client_secret"]
                _ = st.secrets["sdp"]["refresh_token"]
                _ = st.secrets["sdp"]["api_domain"]
                _ = st.secrets["sdp"]["accounts_url"]
            except Exception:
                st.error(
                    "SDP OAuth credentials missing. Please configure secrets."
                )
                st.stop()

            created_count = 0
            updated_count = 0
            fail_count = 0

            status_container = st.container()

            with status_container:
                try:
                    access_token = get_access_token()
                except Exception as auth_err:
                    st.error(f"Authentication error: {str(auth_err)}")
                    st.stop()

                # show visual feedback while parallel execution runs
                with st.spinner("Dispatching tickets to ServiceDesk... Please wait."):
                    # process machines in parallel threads
                    with ThreadPoolExecutor(max_workers=config.MAX_WORKERS) as executor:
                        futures = [
                            executor.submit(process_single_pc, row_tuple, access_token, ticket_template)
                            for row_tuple in final_df.iterrows()
                        ]

                        for future in as_completed(futures):
                            # EMERGENCY STOP CHECK
                            if st.session_state.stop_requested:
                                break

                            res = future.result()
                            st.session_state.dispatch_logs.append(res["log"])

                            if res["status"] == "update":
                                st.markdown(res["html"], unsafe_allow_html=True)
                                updated_count += 1
                            elif res["status"] == "create":
                                st.markdown(res["html"], unsafe_allow_html=True)
                                created_count += 1
                            else:
                                st.error(res["error_msg"])
                                fail_count += 1

            total_handled = created_count + updated_count
            if total_handled > 0:
                st.success(
                    f"Process completed. Created **{created_count}** new ticket(s) "
                    f"and updated **{updated_count}** existing ticket(s)."
                    f"\n\nTotal tickets handled: **{total_handled}**."
                )

        # BACKUP AUDIT LOG (ONLY DISPLAYS IF EMERGENCY STOP IS CLICKED)
        if st.session_state.stop_requested and st.session_state.dispatch_logs:
            st.error("**Emergency Stop Triggered!** Ticket dispatch was stopped.")
            st.markdown("### Tickets Processed Before Interruption:")
            for log_entry in st.session_state.dispatch_logs:
                st.write(f"• {log_entry}")

    except Exception as e:
        st.error(f"Failed to process files. Error details: {str(e)}")